"""Add lead_source to AffiliateProspect

Revision ID: 565d5aabeb74
Revises: c13e97c678ac
Create Date: 2025-06-04 06:53:57.230185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565d5aabeb74'
down_revision: Union[str, None] = 'c13e97c678ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_prospects', sa.Column('lead_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliate_prospects', 'lead_source')
    # ### end Alembic commands ###
