apiVersion: v1
kind: Namespace
metadata:
  name: affiliate-outreach
  labels:
    name: affiliate-outreach
    app.kubernetes.io/name: affiliate-outreach-system
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: agentic-affiliate-system
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    description: "Namespace for the Agentic Affiliate Outreach System"
    contact: "devops@company.com"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: affiliate-outreach-quota
  namespace: affiliate-outreach
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: affiliate-outreach-limits
  namespace: affiliate-outreach
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container
